name: Dependency SUbmission

on:
  workflow_dispatch:
  push:
  schedule:
  - cron: '24 16 * * 6'

permissions: 
  id-token: write
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Dotnet Info
      #   run: dotnet --info
      - name: Build
        run: dotnet restore
      # - name: Build
      #   run: dotnet build
      # - name: Component detection 
      #   if: runner.os != 'Windows'
      #   uses: jhutchings1/component-detection-action@v0.0.1
      - name: Component detection 
        uses: advanced-security/component-detection-dependency-submission-action@feature/handle-null-purls
